### ISSUE TITLE
Feedback on FFmpeg.exe MD5 checksum not matched stored value about FBatch Portable_3.0.9

### ISSUE THREAD

**Issue by jiancaierban** [eibol/ffmpeg_batch#122]
FFmpeg_Batch_AV_Converter_Portable_3.0.9_x64.zip shows "FFmpeg.exe MD5 checksum is not matching stored value."
I downloaded ffmpeg-7.1-full_build.7z from https://www.gyan.dev/ffmpeg/builds. 
The FFmpeg.exe MD5 shows 8FC3669A8DAB286D84D55FDE494CAE8D,but FFmpeg_Batch_AV_Converter_Portable_3.0.9_x64.zip FFmpeg.exe MD5 checksum stored value shows 081ca709d44a3a962aae60f8c17d8d9a.
I can't determine which is correct

**Comment by eibol** [comment]
Hi, actually in portable version that checksum is no longer useful, since ffmpeg.exe is not included anymore.
If you trust your ffmpeg.exe, or download it from official sources, you can check at secutiry and performance "Do not validate ffmpeg".
Current md5 for ffmpeg.exe 7.1 full release is 8fc3669a8dab286d84d55fde494cae8d

**Comment by jiancaierban** [comment]
> Hi, actually in portable version that checksum is no longer useful, since ffmpeg.exe is not included anymore. If you trust your ffmpeg.exe, or download it from official sources, you can check at secutiry and performance "Do not validate ffmpeg". Current md5 for ffmpeg.exe 7.1 full release is 8fc3669a8dab286d84d55fde494cae8d

Roger that.Thank you very much.
