### ISSUE TITLE
Files Not Converting Properly

### ISSUE THREAD

**Issue by Deepesh008** [eibol/ffmpeg_batch#18]
I used to hard encode subtitles using external subtitle files on my anime episodes using Batch subtitles tab with burn subtitles option enabled.
Parameters Used - -c:v hevc_qsv -preset veryfast -global_quality 25 -look_ahead 1 -c:a aac -pix_fmt yuv420p -s hd720
It used to work till version 2.3.8 but not working in newer versions including the latest one v 2.5.0.
It just shows an error in the status tab.
I am not too familiar with parameters, but these used to work in the previous versions till v 2.3.8. Moving back to the previous versions till now.

**Comment by eibol** [comment]
Hi, it may be related to the ffmpg version change from that version on. Current latest ffmpeg is 4.4, maybe hevc_qsv parameters
have changed since then. 

You can run on the console 'ffmpeg -h hevc_qsv' to check encoder capabilities for ffmpeg 4.4.

You can also try saving ffmpeg version from 2.3.8, install 2.5.0 and then replace ffmpeg with previous version.
