### ISSUE TITLE
keep original bitrate

### ISSUE THREAD

**Issue by wyup** [eibol/ffmpeg_batch#67]
I'm trying to batch convert a list of movies with old tv-incompatible codecs (mpeg-4, xvid, divx) to h264-qsv or h265-qsv while maintaining original bitrate of each source, because i don't want to give more bitrate to each file than necessary. I can't seem to find a preset that does this. Could you help? Thanks.
Else I'll try to find a common ground with crf.

**Comment by eibol** [comment]
Hi, there's no preset to keep original bitrate, it would require a custom development to detect source bitrate and resuse it later.
I do not recommend it since bitrate alone is not a good indicator as a common factor, as it can vary a lot depending on source codec, resolution, etc.

I would go with finding a crf and preset that matches your quality/size expectations.
